### ISSUE TITLE
Cloudnet 2 findet spigot nicht

### ISSUE THREAD

**Issue by xXSofortRushXx** [CloudNetService/CloudNet-v2#117]
Guten Tag

ich habe das Problem das Cloudnet 2.0 die Spigot nicht findet wenn ich sie beim server starten aus wähle ich bitte um Hilfe 

log
[22.04.2019 04:21:12] INFO: Choose a Spigot version ["1.7.10", "1.8.8", "1.9.4", "1.10.2", "1.11.2", "1.12.2", "1.13", "1.13.1"]
1.8.8
[22.04.2019 04:21:17] INFO: Downloading spigot.jar...
[22.04.2019 04:21:18] SEVERE: java.io.FileNotFoundException: https://yivesmirror.com/files/spigot/spigot-1.8.8-R0.1-SNAPSHOT-latest.jar
[22.04.2019 04:21:18] SEVERE:  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
[22.04.2019 04:21:18] SEVERE:  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[22.04.2019 04:21:18] SEVERE:  at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
[22.04.2019 04:21:18] SEVERE:  at de.dytanic.cloudnetwrapper.setup.SetupSpigotVersion$1.run(SetupSpigotVersion.java:34)
[22.04.2019 04:21:18] SEVERE:  at de.dytanic.cloudnetwrapper.setup.SetupSpigotVersion$1.run(SetupSpigotVersion.java:24)
[22.04.2019 04:21:18] SEVERE:  at de.dytanic.cloudnetwrapper.setup.SetupSpigotVersion.run(SetupSpigotVersion.java:136)
[22.04.2019 04:21:18] SEVERE:  at de.dytanic.cloudnetwrapper.CloudNetWrapper.bootstrap(CloudNetWrapper.java:130)
[22.04.2019 04:21:18] SEVERE:  at de.dytanic.cloudnetwrapper.bootstrap.CloudBootstrap.main(CloudBootstrap.java:99)
[22.04.2019 04:21:18] SEVERE:  at de.dytanic.cloudnetwrapper.bootstrap.CloudNetLauncher.main(CloudNetLauncher.java:20)

**Comment by Sarsum** [comment]
Moin, 

das Problem liegt daran, dass es Yivesmirror (dort wo die Spigot Server bisher heruntergeladen wurden) nicht mehr gibt.
In einer neueren Version der V2 wurde dies bereits behoben!
Diese findest du unter https://cloudnetservice.eu/cloudnet/version/release/2.1.14.3/ und du kannst auf diese updaten indem du einfach die .jar Dateien vom Wrapper und Master ersetzt!

Ich hoffe ich konnte dir damit helfen.

Viele Grüße und noch einen angenehmen Tag
