### ISSUE TITLE
Fehler beim erstellen eines CloudNet V2 servers

### ISSUE THREAD

**Issue by Pixel-01** [CloudNetService/CloudNet-v2#118]
Hey Leute,

Ich bin dabei einen CloudNet-V2 Server zu erstellen. Jedoch komme ich bei dem Schritt wo die spigot.jar downloadet nicht weiter, denn es kommt dieser Fehler.

------------------------------------------------------------------------------------------------------------------------

Fehler:

[22.04.2019 13:07:01] INFO: Choose a minecraft server version ["paper" (coming soon), "spigot"]
spigot
[22.04.2019 13:07:15] INFO: Choose a Spigot version ["1.7.10", "1.8.8", "1.9.4", "1.10.2", "1.11.2", "1.12.2", "1.13", "1.13.1", "1.13.2"]
1.8.8
[22.04.2019 13:07:18] INFO: Downloading spigot.jar...
[22.04.2019 13:07:20] SEVERE: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[22.04.2019 13:07:20] SEVERE:   at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[22.04.2019 13:07:20] SEVERE:   at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
[22.04.2019 13:07:20] SEVERE:   at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
[22.04.2019 13:07:20] SEVERE:   at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
[22.04.2019 13:07:20] SEVERE:   at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
[22.04.2019 13:07:20] SEVERE:   at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
[22.04.2019 13:07:20] SEVERE:   at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
[22.04.2019 13:07:20] SEVERE:   at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
[22.04.2019 13:07:20] INFO: Trying to connect ###.###.###.##:1410
[22.04.2019 13:07:20] SEVERE:   at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
[22.04.2019 13:07:20] SEVERE:   at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
[22.04.2019 13:07:20] SEVERE:   at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
[22.04.2019 13:07:20] SEVERE:   at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
[22.04.2019 13:07:20] SEVERE:   at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
[22.04.2019 13:07:20] SEVERE:   at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[22.04.2019 13:07:20] SEVERE:   at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
[22.04.2019 13:07:20] SEVERE:   at de.dytanic.cloudnetwrapper.setup.SetupSpigotVersion$1.run(SetupSpigotVersion.java:33)
[22.04.2019 13:07:20] SEVERE:   at de.dytanic.cloudnetwrapper.setup.SetupSpigotVersion$1.run(SetupSpigotVersion.java:24)
[22.04.2019 13:07:20] SEVERE:   at de.dytanic.cloudnetwrapper.setup.SetupSpigotVersion.run(SetupSpigotVersion.java:104)
[22.04.2019 13:07:20] SEVERE:   at de.dytanic.cloudnetwrapper.CloudNetWrapper.bootstrap(CloudNetWrapper.java:129)
[22.04.2019 13:07:20] SEVERE:   at de.dytanic.cloudnetwrapper.bootstrap.CloudBootstrap.main(CloudBootstrap.java:99)
[22.04.2019 13:07:20] SEVERE:   at de.dytanic.cloudnetwrapper.bootstrap.CloudNetLauncher.main(CloudNetLauncher.java:20)
[22.04.2019 13:07:20] SEVERE: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[22.04.2019 13:07:20] SEVERE:   at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
[22.04.2019 13:07:20] SEVERE:   at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
[22.04.2019 13:07:20] SEVERE:   at sun.security.validator.Validator.validate(Validator.java:260)
[22.04.2019 13:07:20] SEVERE:   at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
[22.04.2019 13:07:20] SEVERE:   at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
[22.04.2019 13:07:20] SEVERE:   at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
[22.04.2019 13:07:20] SEVERE:   at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
[22.04.2019 13:07:20] SEVERE:   ... 16 more
[22.04.2019 13:07:20] SEVERE: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[22.04.2019 13:07:20] SEVERE:   at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146)
[22.04.2019 13:07:20] SEVERE:   at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
[22.04.2019 13:07:20] SEVERE:   at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
[22.04.2019 13:07:20] SEVERE:   at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
[22.04.2019 13:07:20] SEVERE:   ... 22 more

------------------------------------------------------------------------------------------------------------------------

Ich hoffe ihr könnt mir helfen.

MFG,
Pixel-01

**Comment by juliarn** [comment]
Hey, hast du eventuell "-ssl" in deiner start.sh stehen? Daran könnte es liegen. Du kannst gerne unserem Discord beitreten, dann können wir dir leichter helfen.

**Comment by Pixel-01** [comment]
@realPanamo Leider habe ich kein Discord
Nein in meinen start.sh ist kein -ssl
---------------------------------------------------------------------------------------------------------------------------------
Wrapper start.sh
#!/bin/sh
screen -S Wrapper-1 java -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:CompileThreshold=100 -XX:MaxPermSize=256M -Xmx64m -jar CloudNet-Wrapper.jar

Master start.sh
#!/bin/sh
screen -S CloudNet java -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:CompileThreshold=100 -XX:MaxPermSize=256M -Xmx128m -jar CloudNet-Master.jar

**Comment by juliarn** [comment]
Besitzt du denn die aktuellste Version, also 2.1.14.3? Wenn ja, schick doch mal deine config.yml im Master

**Comment by GiantTreeLP** [comment]
Und wenn du ein Linux nutzt, stell sicher, dass die CA Zertifikate für Java installiert sind (`apt install ca-certificates-java` für Debian und Derivate)

**Comment by Pixel-01** [comment]
@GiantTreeLP habe ich eben installiert, der Fehler ist leider immer noch vorhanden.

@realPanamo Ja habe ich.

---------------------------------------------------------------------------------------------------------------------------------

Config.yml


general:
  auto-update: false
  dynamicservices: false
  server-name-splitter: '-'
  notify-service: true
  disabled-modules: []
  cloudGameServer-wrapperList:
  - Wrapper-1
server:
  hostaddress: ###.###.###.##
  ports:
  - 1410
  webservice:
    hostaddress: ###.###.###.##
    port: 1420
cloudnet-statistics:
  enabled: true
  uuid: 7979055f-93bd-4c1e-8d81-00225defb015
networkproperties:
  test: true

**Comment by derklaro** [comment]
Falls der Fehler weiterhin auftritt, würde ich dir empfehlen die spigot selber herunterzuladen. Dann kannst du die Cloud wenigstens benutzen, während der Fehler gesucht wird.

**Comment by GiantTreeLP** [comment]
Am besten auch noch die version deiner cloud dazuschreiben, dann können wir da mehr zu sagen

**Comment by byRoadrunner** [comment]
Closed due to inactivity. If there are further questions feel free to reopen the issue.
