### ISSUE TITLE
Runtime Exception on PlayerExecutor

### ISSUE THREAD

**Issue by TheMeinerLP** [CloudNetService/CloudNet-v2#225]
On the Server start is something wrong with the player executor
The Interface can't be instantiated!
Stacktrace:
```
[24.12.2019 13:49:18] INFO: [Lobby-1] java.lang.RuntimeException: Unable to invoke no-args constructor for interface de.dytanic.cloudnet.lib.player.PlayerExecutor. Register an InstanceCreator with Gson for this type may fix this problem.
[24.12.2019 13:49:18] INFO: [Lobby-1]   at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:226) ~[spigot.jar:git-Paper-237]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210) ~[spigot.jar:git-Paper-237]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[spigot.jar:git-Paper-237]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[spigot.jar:git-Paper-237]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at com.google.gson.Gson.fromJson(Gson.java:887) ~[spigot.jar:git-Paper-237]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at com.google.gson.Gson.fromJson(Gson.java:952) ~[spigot.jar:git-Paper-237]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at de.dytanic.cloudnet.lib.utility.document.Document.getObject(Document.java:360) ~[?:?]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at de.dytanic.cloudnet.api.CloudAPI.getOnlinePlayer(CloudAPI.java:1415) ~[?:?]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at de.dytanic.cloudnet.bridge.internal.listener.bukkit.BukkitListener.handle0(BukkitListener.java:58) ~[?:?]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[spigot.jar:git-Paper-237]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[spigot.jar:git-Paper-237]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Paper-237]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[spigot.jar:git-Paper-237]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at net.minecraft.server.v1_14_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:311) ~[spigot.jar:git-Paper-237]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at net.minecraft.server.v1_14_R1.LoginListener$1.run(LoginListener.java:212) ~[spigot.jar:git-Paper-237]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_202]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_202]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
[24.12.2019 13:49:18] INFO: [Lobby-1] Caused by: java.lang.UnsupportedOperationException: Interface can't be instantiated! Interface name: de.dytanic.cloudnet.lib.player.PlayerExecutor
[24.12.2019 13:49:18] INFO: [Lobby-1]   at com.google.gson.internal.UnsafeAllocator.assertInstantiable(UnsafeAllocator.java:117) ~[spigot.jar:git-Paper-237]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at com.google.gson.internal.UnsafeAllocator.access$000(UnsafeAllocator.java:31) ~[spigot.jar:git-Paper-237]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:49) ~[spigot.jar:git-Paper-237]
[24.12.2019 13:49:18] INFO: [Lobby-1]   at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:223) ~[spigot.jar:git-Paper-237]
[24.12.2019 13:49:18] INFO: [Lobby-1]   ... 18 more
```

**Comment by GiantTreeLP** [comment]
Would you just stop opening issues for things not even in the development branch that have already been fixed?
