### ISSUE TITLE
Master Stop Wrapper connection issue

### ISSUE THREAD

**Issue by TheMeinerLP** [CloudNetService/CloudNet-v2#236]
Description:
This issue coming up, if the master stopping before the wrapper.

CloudNet Version: 2.2.0
Java Version: 
```
openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment Zulu11.37+17-CA (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.37+17-CA (build 11.0.6+10-LTS, mixed mode)
```
System Info:
```
Hostname:                                      XXXX-HP-LT
Betriebssystemname:                            Microsoft Windows 10 Pro
Betriebssystemversion:                         10.0.18363 Nicht zutreffend Build 18363
Betriebssystemhersteller:                      Microsoft Corporation
Betriebssystemkonfiguration:                   Mitglied der Domäne/Arbeitsgruppe
Betriebssystem-Buildtyp:                       Multiprocessor Free
Registrierter Benutzer:                        meinerlp
Registrierte Organisation:                     Nicht zutreffend
Produkt-ID:                                    00330-50000-00000-AAOEM
Ursprüngliches Installationsdatum:             05.01.2020, 14:17:22
Systemstartzeit:                               23.02.2020, 08:40:05
Systemhersteller:                              HP
Systemmodell:                                  HP EliteBook 830 G5
Systemtyp:                                     x64-based PC
Prozessor(en):                                 1 Prozessor(en) installiert.
                                               [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~1792 MHz
BIOS-Version:                                  HP Q78 Ver. 01.08.01, 18.07.2019
Windows-Verzeichnis:                           C:\Windows
System-Verzeichnis:                            C:\Windows\system32
Startgerät:                                    \Device\HarddiskVolume1
Systemgebietsschema:                           de;Deutsch (Deutschland)
Eingabegebietsschema:                          de;Deutsch (Deutschland)
Zeitzone:                                      (UTC-05:00) Eastern Zeit (USA & Kanada)
Gesamter physischer Speicher:                  32.611 MB
Verfügbarer physischer Speicher:               22.696 MB
Virtueller Arbeitsspeicher: Maximale Größe:    37.475 MB
Virtueller Arbeitsspeicher: Verfügbar:         26.732 MB
Virtueller Arbeitsspeicher: Zurzeit verwendet: 10.743 MB
Auslagerungsdateipfad(e):                      C:\pagefile.sys
Domäne:                                        XXXX.XXXX
Anmeldeserver:                                 \\XXXX
Hotfix(es):                                    9 Hotfix(e) installiert.
                                               [01]: KB4534132
                                               [02]: KB4497727
                                               [03]: KB4516115
                                               [04]: KB4517245
                                               [05]: KB4524569
                                               [06]: KB4528759
                                               [07]: KB4537759
                                               [08]: KB4538674
                                               [09]: KB4532693
Anforderungen für Hyper-V:                     Erweiterungen für den VM-Überwachungsmodus: Ja
                                               Virtualisierung in Firmware aktiviert: Ja
                                               Adressübersetzung der zweiten Ebene: Ja
                                               Datenausführungsverhinderung verfügbar: Ja
``` 
Stacktrace:
```
[23.02.2020 11:46:16] INFO: Failed to connect... [1]
[23.02.2020 11:46:16] SEVERE: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /169.254.148.200:1410
[23.02.2020 11:46:16] SEVERE: Caused by: java.net.ConnectException: Connection refused: no further information
[23.02.2020 11:46:16] SEVERE:   at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[23.02.2020 11:46:16] SEVERE:   at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
[23.02.2020 11:46:16] SEVERE:   at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
[23.02.2020 11:46:16] SEVERE:   at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[23.02.2020 11:46:16] SEVERE:   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
[23.02.2020 11:46:16] SEVERE:   at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
[23.02.2020 11:46:16] SEVERE:   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
[23.02.2020 11:46:16] SEVERE:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[23.02.2020 11:46:16] SEVERE:   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[23.02.2020 11:46:16] SEVERE:   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[23.02.2020 11:46:16] SEVERE:   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[23.02.2020 11:46:16] SEVERE:   at java.base/java.lang.Thread.run(Thread.java:834)
[23.02.2020 11:46:18] INFO: Failed to connect... [2]
[23.02.2020 11:46:18] SEVERE: io.netty.util.concurrent.BlockingOperationException: DefaultChannelPromise@4cab76e6(incomplete)
[23.02.2020 11:46:18] SEVERE:   at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:461)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.DefaultChannelPromise.checkDeadLock(DefaultChannelPromise.java:159)
[23.02.2020 11:46:18] SEVERE:   at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:246)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:131)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:30)
[23.02.2020 11:46:18] SEVERE:   at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:403)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:119)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:30)
[23.02.2020 11:46:18] SEVERE:   at de.dytanic.cloudnet.lib.network.NetworkConnection.tryConnect(NetworkConnection.java:210)
[23.02.2020 11:46:18] SEVERE:   at de.dytanic.cloudnet.lib.network.NetworkConnection.tryConnect(NetworkConnection.java:188)
[23.02.2020 11:46:18] SEVERE:   at de.dytanic.cloudnetwrapper.CloudNetWrapper.onShutdownCentral(CloudNetWrapper.java:136)
[23.02.2020 11:46:18] SEVERE:   at de.dytanic.cloudnetwrapper.CloudNetWrapper.lambda$new$0(CloudNetWrapper.java:82)
[23.02.2020 11:46:18] SEVERE:   at de.dytanic.cloudnet.lib.network.NetDispatcher.channelInactive(NetDispatcher.java:35)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:260)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:239)
[23.02.2020 11:46:18] SEVERE:   at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:386)
[23.02.2020 11:46:18] SEVERE:   at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:351)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:260)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:239)
[23.02.2020 11:46:18] SEVERE:   at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:386)
[23.02.2020 11:46:18] SEVERE:   at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:351)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:260)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:239)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:260)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
[23.02.2020 11:46:18] SEVERE:   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[23.02.2020 11:46:18] SEVERE:   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[23.02.2020 11:46:18] SEVERE:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
[23.02.2020 11:46:18] SEVERE:   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[23.02.2020 11:46:18] SEVERE:   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[23.02.2020 11:46:18] SEVERE:   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[23.02.2020 11:46:18] SEVERE:   at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by GiantTreeLP** [comment]
Closed by 6d4ee74fc9a0a3ff6dfa7916bbc52a8f585860a6
